### PR TITLE
Add option to specify kubectl version

### PR DESCRIPTION
**Pull request by anthonycrobinson**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [ ] Examples have been added for any significant new features
- [ ] README has been updated, if necessary

### Motivation, issues

kubectl v1.24.0 introduces breaking change to api version.
fixes https://github.com/CircleCI-Public/aws-eks-orb/issues/67

### Description

- add kubectl-version parameter to commands that install kubectl
- add kubectl-version parameter to jobs that install kubectl

### CODE REVIEW

**Comment by KyleTryon** [comment]
Excellent work @anthonycrobinson, thank you for the contribution, running the tests now.

**Comment by anthonycrobinson** [comment]
Looks like we'll have to update the tests, as they are failing with exactly the issue this PR addresses. I can look into the test suite later to see if I can update them to call the updated kubectl install

**Comment by anthonycrobinson** [comment]
@KyleTryon 
The create cluster commands are also going to need the parameters. I do not like having that hard coded all over the place, and do not know of a way to pass it once for all tests.
What do you think about defaulting to v1.21.0? (I don't love the idea, but would keep it cleaner)

**Comment by KyleTryon** [comment]
> @KyleTryon The create cluster commands are also going to need the parameters. I do not like having that hard coded all over the place, and do not know of a way to pass it once for all tests. What do you think about defaulting to v1.21.0? (I don't love the idea, but would keep it cleaner)

What was your thinking on picking 1.21.0 vs the latest version `v1.24.0`. Hard coding version defaults I don't have an issue with, it keeps the orb more immutable, it may even be better to have the user manually select "latest" in some cases.

As for duplicating parameter code.. its an unfortunate thing but also keeps the documentation easy.

**Comment by anthonycrobinson** [comment]
1.21 was arbitrary. 1.24 is what is breaking. EKS doesn't support 1.24 yet, and the 1.24 binary dropped support for the v1.alpha api version as noted in the issue. latest is how I currently have it defaulting. 1.23 would be the latest that would fix the issue.

**Comment by anthonycrobinson** [comment]
1.22 would be what I would recommend for default if we were going to default to a version. 1.22.6 is the latest supported version for EKS as of right now

**Comment by anthonycrobinson** [comment]
Reverted test changes, locked to v1.22.0
I do not see the QuickStart instructions in this repo. I assume these are updated on CircleCI Orb setup. This is where I would put note about kubectl locked version

**Comment by anthonycrobinson** [comment]
@KyleTryon at your convenience. Assuming tests were passing before, tests should pass with defaulting to 1.22 (latest EKS)

**Comment by anthonycrobinson** [comment]
Looks like manual CF stack cleanup is required 😭 
I don't think I can help with those fails

**Comment by anthonycrobinson** [comment]
The tests don't always use the install from the orb :( hardcoded all kubernetes/install to v1.22.0, updated example to match.
Last one for me tonight. I'll check in tomorrow am.
@KyleTryon

**Comment by edbergavera** [comment]
I can confirm that it works on `kubectl v1.22.9` at least on macOS Homebrew.

**Comment by KyleTryon** [comment]
Thank you all for the assistance 🙇. @anthonycrobinson let me know if you would like anyone to take over. thank you again 🙇

**Comment by anthonycrobinson** [comment]
@KyleTryon is there something else you wanted done? The other places where kubectl was failing in the tests should be resolved.

**Comment by edbergavera** [comment]
I wonder if I should wait for this PR to be merged or create my Orb.

**Comment by KyleTryon** [comment]
@anthonycrobinson 

> @KyleTryon is there something else you wanted done? The other places where kubectl was failing in the tests should be resolved.

Apologies I thought I had re-ran the tests since the change, I am not sure now, so re-triggering: https://app.circleci.com/pipelines/github/CircleCI-Public/aws-eks-orb/689/workflows/1bbe4a63-a9b6-4fff-bf46-49786e504469

**Comment by anthonycrobinson** [comment]
@KyleTryon I'm not sure what to do about invalid endpoint for delete cluster when it succeeded in other tests. and can't imagine why the same steps for both of the failed tests passed in other tests.

**Comment by anthonycrobinson** [comment]
I misspoke. The helm chart is not installed in any other tests. I still do not believe that they are related.

**Comment by anthonycrobinson** [comment]
Most recent merged PR failed spectacularly.
https://github.com/CircleCI-Public/aws-eks-orb/runs/5956335651

**Comment by KyleTryon** [comment]
> Most recent merged PR failed spectacularly. https://github.com/CircleCI-Public/aws-eks-orb/runs/5956335651

Ah I believe I know of the history of what happened here. Here's what we'll do for the time being. this orb also needs to be updated to Orb Tools 11. And the state of the tests at the moment is... apparently a bit of a mess. @edbergavera has confirmed the fix and I do not want to hold this relatively small change back from this as folks are waiting. Lets merge this, I will create the task of doing likely a major version update in the near future and work to replace/fix the tests. As you mentioned, your change here is not related to the issues we are seeing. Sorry for the delay!

**Pull request merged**
