### PR TITLE
Use newer AWS CLI.

### PR DESCRIPTION
**Pull request by felicianotech**

### CODE REVIEW

**Comment by lokst** [comment]
Thanks @felicianotech! Looks like circleci/aws-cli@0.1 resolves to the latest 0.1.x version (0.1.14) but I was thinking it would be good to explicitly reference 0.1.14 so that the newly published version of the eks orb will always use the same version of the aws-cli orb

**Comment by lokst** [comment]
Documentation note: version 0.1.14 of the aws-cli orb contains the changes in https://github.com/CircleCI-Public/aws-cli-orb/pull/17

**Comment by danburkert** [comment]
This is a really painful issue for my organization, where this crate is causing >45s of wasted CI time per job unnecessarily installing aws-cli via pip.  I've opened #30 to try and get the ball rolling here.

**Comment by gmemstr** [comment]
AWS CLI orb is 1.x for this orb

**Pull request closed without merging**
